#lang errortrace typed/racket/no-check

(require "types.rkt")
(require file/sha1)
(require binaryio/integer)
(require errortrace)

(provide (all-defined-out))

; Global variables
(define byte-offset 0)
(define label-map (make-hash '()))

(: opcode-table (Listof opcode))
(define opcode-table
  `(,(opcode #x00 'STOP)
    ,(opcode #x01 'ADD)
    ,(opcode #x02 'MUL)
    ,(opcode #x03 'SUB)
    ,(opcode #x04 'DIV)
    ,(opcode #x05 'SDIV)
    ,(opcode #x06 'MOD)
    ,(opcode #x07 'SMOD)
    ,(opcode #x08 'ADDMOD)
    ,(opcode #x09 'MULMOD)
    ,(opcode #x0a 'EXP)
    ,(opcode #x0b 'SIGNEXTEND)
    
    ,(opcode #x10 'LT)
    ,(opcode #x11 'GT)
    ,(opcode #x12 'SLT)
    ,(opcode #x13 'LGT)
    ,(opcode #x14 'EQ)
    ,(opcode #x15 'ISZERO)
    ,(opcode #x16 'AND)
    ,(opcode #x17 'OR)
    ,(opcode #x18 'XOR)
    ,(opcode #x19 'NOT)
    ,(opcode #x1a 'BYTE)
    
    ,(opcode #x20 'SHA3)
    
    ,(opcode #x30 'ADDRESS)
    ,(opcode #x31 'BALANCE)
    ,(opcode #x32 'ORIGIN)
    ,(opcode #x33 'CALLER)
    ,(opcode #x34 'CALLVALUE)
    ,(opcode #x35 'CALLDATALOAD)
    ,(opcode #x36 'CALLDATASIZE)
    ,(opcode #x37 'CALLDATACOPY)
    ,(opcode #x38 'CODESIZE)
    ,(opcode #x39 'CODECOPY)
    ,(opcode #x3a 'GASPRICE)
    ,(opcode #x3b 'EXTCODESIZE)
    ,(opcode #x3c 'EXTCODECOPY)
    
    ,(opcode #x40 'BLOCKHASH)
    ,(opcode #x41 'COINBASE)
    ,(opcode #x42 'TIMESTAMP)
    ,(opcode #x43 'NUMBER)
    ,(opcode #x44 'DIFFICULTY)
    ,(opcode #x45 'GASLIMIT)
    
    ,(opcode #x50 'POP)
    ,(opcode #x51 'MLOAD)
    ,(opcode #x52 'MSTORE)
    ,(opcode #x53 'MSTORE8)
    ,(opcode #x54 'SLOAD)
    ,(opcode #x55 'SSTORE)
    ,(opcode #x56 'JUMP)
    ,(opcode #x57 'JUMPI)
    ,(opcode #x58 'PC)
    ,(opcode #x59 'MSIZE)
    ,(opcode #x5a 'GAS)
    ,(opcode #x5b 'JUMPDEST)
    
    ,(opcode #x60 'PUSH1)
    ,(opcode #x61 'PUSH2)
    ,(opcode #x62 'PUSH3)
    ,(opcode #x63 'PUSH4)
    ,(opcode #x64 'PUSH5)
    ,(opcode #x65 'PUSH6)
    ,(opcode #x66 'PUSH7)
    ,(opcode #x67 'PUSH8)
    ,(opcode #x68 'PUSH9)
    ,(opcode #x69 'PUSH10)
    ,(opcode #x6a 'PUSH11)
    ,(opcode #x6b 'PUSH12)
    ,(opcode #x6c 'PUSH13)
    ,(opcode #x6d 'PUSH14)
    ,(opcode #x6e 'PUSH15)
    ,(opcode #x6f 'PUSH16)
    ,(opcode #x70 'PUSH17)
    ,(opcode #x71 'PUSH18)
    ,(opcode #x72 'PUSH19)
    ,(opcode #x73 'PUSH20)
    ,(opcode #x74 'PUSH21)
    ,(opcode #x75 'PUSH22)
    ,(opcode #x76 'PUSH23)
    ,(opcode #x77 'PUSH24)
    ,(opcode #x78 'PUSH25)
    ,(opcode #x79 'PUSH26)
    ,(opcode #x7a 'PUSH27)
    ,(opcode #x7b 'PUSH28)
    ,(opcode #x7c 'PUSH29)
    ,(opcode #x7d 'PUSH30)
    ,(opcode #x7e 'PUSH31)
    ,(opcode #x7f 'PUSH32)
    
    ,(opcode #x80 'DUP1)
    ,(opcode #x81 'DUP2)
    ,(opcode #x82 'DUP3)
    ,(opcode #x83 'DUP4)
    ,(opcode #x84 'DUP5)
    ,(opcode #x85 'DUP6)
    ,(opcode #x86 'DUP7)
    ,(opcode #x87 'DUP8)
    ,(opcode #x88 'DUP9)
    ,(opcode #x89 'DUP10)
    ,(opcode #x8a 'DUP11)
    ,(opcode #x8b 'DUP12)
    ,(opcode #x8c 'DUP13)
    ,(opcode #x8d 'DUP14)
    ,(opcode #x8e 'DUP15)
    ,(opcode #x8f 'DUP16)
    
    ,(opcode #x90 'SWAP1)
    ,(opcode #x91 'SWAP2)
    ,(opcode #x92 'SWAP3)
    ,(opcode #x93 'SWAP4)
    ,(opcode #x94 'SWAP5)
    ,(opcode #x95 'SWAP6)
    ,(opcode #x96 'SWAP7)
    ,(opcode #x97 'SWAP8)
    ,(opcode #x98 'SWAP9)
    ,(opcode #x99 'SWAP10)
    ,(opcode #x9a 'SWAP11)
    ,(opcode #x9b 'SWAP12)
    ,(opcode #x9c 'SWAP13)
    ,(opcode #x9d 'SWAP14)
    ,(opcode #x9e 'SWAP15)
    ,(opcode #x9f 'SWAP16)
    
    ,(opcode #xa0 'LOG0)
    ,(opcode #xa1 'LOG1)
    ,(opcode #xa2 'LOG2)
    ,(opcode #xa3 'LOG3)
    ,(opcode #xa4 'LOG3)
    
    ,(opcode #xf0 'CREATE)
    ,(opcode #xf1 'CALL)
    ,(opcode #xf2 'CALLCODE)
    ,(opcode #xf3 'RETURN)
    ,(opcode #xf4 'DELEGATECALL)
    
    ,(opcode #xfd 'PUSH)
    ,(opcode #xfe 'INVALID)
    ,(opcode #xff 'SELFDESTRUCT)
    ))

(define opcodes-by-sym
  (make-hash (map (lambda (op)
                    (cons (opcode-name op) op))
                  opcode-table)))

(define opcodes-by-byte
  (make-hash (map (lambda (op)
                    (cons (opcode-byte op) op))
                  opcode-table)))

(: serialize-print (-> EthInstructions Void))
(define (serialize-print is)
  (write (bytes->hex-string (serialize is))))

(: serialize (-> EthInstructions bytes))
(define (serialize is)
  (if (null? is)
      (bytes)
      (bytes-append (serialize-one (car is))
                    (serialize     (cdr is)))))

(: serialize-one (-> EthInstruction bytes))
(define (serialize-one i)
  (set! byte-offset (+ 1 byte-offset))
  (cond ((eth-asm?     i) (serialize-opcode (lookup-opcode (eth-asm-name i))))
        ((eth-push?    i) (serialize-push i))
        ((eth-unknown? i) (bytes i))
        ((label?       i) (serialize-label i))
        (else
         (error "Unknown EthInstruction - serialize-one:" i))))

(: serialize-opcode (-> opcode bytes))
(define (serialize-opcode op)
  (bytes (opcode-byte op)))

(: serialize-push (-> eth-push bytes))
(define (serialize-push push)
  (let ((op (lookup-push-opcode push)))
    (bytes-append (bytes (opcode-byte op))
                  (integer->bytes (push-true-value push)
                                  (eth-push-size push)
                                  #f)))) ; signed?

(: serialize-label (-> label bytes))
(define (serialize-label lbl)
  (remember-label lbl)
  (bytes))

(define newline (bytes 10))

(: lookup-opcode (-> Symbol opcode))
(define (lookup-opcode sym)
  (dict-ref opcodes-by-sym sym))

(: lookup-push-opcode (-> eth-push opcode))
(define (lookup-push-opcode push)
  (dict-ref opcodes-by-byte (+ #x5f (eth-push-size push))))

(: remember-label (-> label Void))
(define (remember-label lbl)
  (dict-set! label-map (label-name lbl) byte-offset))

(: push-true-value (-> eth-push integer))
#| push-true-value:
Either a label or integer can be pushed onto the stack.
* An integer is emitted in big-endian form with the given size.
* A label is either 0 if the label is unknown, or the known value.
* Label values become known when the assembler encounters one. A "current position" global counter is the value.
|#
(define (push-true-value push)
  (let ((val (eth-push-value push)))
    (if (symbol? val)
        (dict-ref label-map val 0)
        val)))
;; (remember-label (label 'derp))
;; (push-true-value (eth-push 5 'derp))
